<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32758" started-at="2015-04-21T05:48:12Z" finished-at="2015-04-21T05:48:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32758" started-at="2015-04-21T05:48:12Z" finished-at="2015-04-21T05:48:45Z">
      <class name="org.utest.Tests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.utest.Tests@43ee72e6]" name="setUp" is-config="true" duration-ms="6948" started-at="2015-04-21T01:48:12Z" finished-at="2015-04-21T01:48:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test_1()[pri:0, instance:org.utest.Tests@43ee72e6]" name="test_1" duration-ms="24880" started-at="2015-04-21T01:48:19Z" finished-at="2015-04-21T01:48:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[arteficial fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: arteficial fail
	at org.testng.Assert.fail(Assert.java:94)
	at org.utest.Tests.test_1(Tests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.utest.Tests@43ee72e6]" name="tearDown" is-config="true" duration-ms="930" started-at="2015-04-21T01:48:44Z" finished-at="2015-04-21T01:48:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.utest.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
